# SPDX-License-Identifier: Apache-2.0
resources:
- ./kustomization

configMapGenerator:
- name: aws-firehose-repeater-cmd
  options:
    disableNameSuffixHash: true
  files:
  - aws-firehose-repeater.bash

secretGenerator:
- name: aws-firehose-repeater-env
  envs:
  - config.env
