apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-firehose-repeater
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-firehose-repeater
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-firehose-repeater
    spec:
      serviceAccountName: aws-firehose-repeater
      containers:
      - name: aws-firehose-repeater
        image: ghcr.io/wesselatwork/aws-firehose-repeater:latest
        args:
        - |
            failure=0;
            touch /tmp/healthy;
            echo "STARTING";
            while (true); do
              bash ./aws-firehose-repeater.bash;
              if [ $? -eq 0 ]; then
                failure=0;
                touch /tmp/healthy;
                sleep 900;
              else
                failure=$((failure + 1));
                echo "FAILED ${failure}";
                rm -f /tmp/healthy;
                sleep 1;
              fi
            done;
        workingDir: /usr/local/bin
        readinessProbe:
          failureThreshold: 3
          exec:
            command:
            - test
            - -f
            - /tmp/healthy
        livenessProbe:
          exec:
            command:
            - /bin/true
        startupProbe:
          failureThreshold: 3
          exec:
            command:
            - test
            - -f
            - /tmp/healthy
        resources:
          requests:
            memory: 96Mi
          limits:
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp-mem
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: tmp-mem
        emptyDir:
          medium: Memory
