# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# NOTE: config.env needs to exist.

secretGenerator:
- name: aws-firehose-repeater-env
  envs:
  - config.env

patches:
  - path: deployment.yaml
