# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
- name: aws-firehose-repeater-cmd
  options:
    disableNameSuffixHash: true
  files:
  - aws-firehose-repeater.bash

patches:
  - path: deployment.yaml
