name: Podman Builder

on:
  # runs every monday at 4 am
  schedule:
    - cron: "0 4 * * 1"
  push:
    branches: [ $default-branch ]
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch: {}


jobs:
  build:

    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{secrets.GITHUB_TOKEN}}

      - name: Install Tools and Info
        run: |
          lsb_release -a
          task install:tools
          task versioninfo

      - name: Login to Registry
        run: echo ${{secrets.GITHUB_TOKEN}} | task podman:login -- ${{github.actor}}

      - name: Build Image
        env:
          OWNER: ${{github.repository_owner}}
        run: task podman:build NAMESPACE=${OWNER,,} DATETIME="$(date -u --iso-8601=seconds)"
